# Generated by Django 3.2rc1 on 2021-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_genre', models.CharField(max_length=250)),
                ('movie_description', models.CharField(max_length=1000)),
                ('movie_rating', models.IntegerField()),
                ('movie_price', models.IntegerField()),
            ],
        ),
    ]
