# Generated by Django 3.2rc1 on 2021-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_price',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_photo',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(max_length=2000),
        ),
    ]
