# Generated by Django 3.2rc1 on 2021-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20210623_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.IntegerField(default=0),
        ),
    ]
