# Generated by Django 3.2rc1 on 2021-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20210623_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
