# Generated by Django 3.2rc1 on 2021-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20210915_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_comming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
